import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "1811 Labs Assignment 01",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${inter.className} flex flex-col items-center bg-[#090725]`}
			>
				<div className="absolute top-0 -z-10">
					<img
						src="/hero-bg.png"
						alt="bg-img"
						className="w-screen h-screen md:h-full"
					/>
				</div>

				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
